## Database Properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banco_controle?allowPublicKeyRetrieval=true&useSSL=false
    username: master
    password: master
    driver-class-name: com.mysql.cj.jdbc.Driver

  ## Hibernate Properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    restart:
      enabled: true

server:
  port: 8090
  servlet:
    contextPath: /api/app-order